[package]
name = "rust-cache-benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
cached = "0.54.0"
lru = "0.13.0"
memory-stats = "1.2.0"
parking_lot = "0.12.3"
quick_cache = "0.6.10"
rayon = "1.10.0"
tabled = "0.18.0"
